# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Unit Name', max_length=25, verbose_name='Unit Name')),
                ('abbrev', models.CharField(help_text='Enter Unit Abbreviation', max_length=10, verbose_name='Unit Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Unitgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitgroup', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='unitgroup',
            field=models.ManyToManyField(to='items.Unitgroup'),
        ),
    ]
